# Docker compose version
version: "3" #<Do not change>#<Do not change>
services:
  # Name of the docker container server
  paypay-ppc-server:
    image: ppc-point-payment #<Do not change>Name of the docker image source
    build:
      context: . #<Do not change>
    container_name: paypay-ppc-server #<Do not change>Desired name of the container ran in docker
    # image: paypay-payment-selection #<Do not change>Name of the docker image source
    user: appuser #<Do not change>
    #<Only for linux host>Enable the docker container to access the host network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    #Forwarding the application default port to the desired port.
    ports:
      #5050 is the machine/computer port, 5000 is the application port
      - "5050:5000"
    expose:
      - "5050" #exposing the port that will be used
    restart: unless-stopped #<Do not change>
    #Storage that will be used in the physical host.
    volumes:
      #When not using Docker Desktop (WSL or native Linux), please change the "appuser" with the linux username
      - ./ProgramData/PaperCut-Charge:/home/appuser/main_app/app/static/uploads

    #<Please adjust these variables>Environment variables for the customers
    environment:
      PRODUCTION: 1
      PUBLIC_URL: "http://host.docker.internal:5000" #url that can be accessed by the Payment Provider to receive notification
      PAPERCUT_SERVER: "http://192.168.12.64:9191"
      PAPERCUT_AUTH_TOKEN: "12345678"
      DATABASE: "" #postgresql or mysql
      DB_SERVER: "" #127.0.0.1
      DB_PORT: "" #5432
      DB_NAME: "" #ppc_point_payment
      DB_USERNAME: "" #root
      DB_PASS: "" #
      ACCESS_USERNAME: "admin" #username to access the payment configuration page
      ACCESS_PASSWORD: "admin123" #password to access the payment configuration page
      TZ: Asia/Tokyo #default timezone for the log timestamp
      MAIL_SERVER: "" #email for receiving & sending notification
      MAIL_PORT: "" #Port of the email server
      MAIL_USE_TLS: "" #True or False
      MAIL_USE_SSL: "" #True or False
      MAIL_USERNAME: "" #username/email for authenticating to the mail server
      MAIL_PASSWORD: "" #password of the email address
      MAIL_DEFAULT_SENDER: "" #email address that will be used for sending notification
      MAIL_DEFAULT_ADMINISTRATOR: "" #email address that will be used for receiving

  #Nginx web server
  nginx:
    image: nginx #<Do not change>
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro #<Do not change> NGINX configuration
      - ./nginx/certs:/etc/nginx/certs:ro #<Do not change> SSL Certificate location
    depends_on:
      - paypay-ppc-server #<Do not change> Name of the app container
    ports:
      - "80:80"
      - "443:443"
      - "5055:5055"
    restart: always
